#!/bin/bash -l

. ~/dyndoc/bin/DyndocStudio.bash_profile

case $1 in
update)
gem specific_install https://github.com/rcqls/dyndoc.git;;
ruby|gem|irb|R|rake)
$* ;;
cli)
shift
dyndoc-client $*;;
srv)
shift
dyndoc-daemon $*;;
*)
dyndoc-ruby $*;;
esac