#!/bin/bash -l

. /Applications/DyndocStudio.app/Contents/DyndocTools/bin/DyndocStudio.bash_profile

case $1 in
gem specific_install https://github.com/rcqls/dyndoc.git;;
ruby|gem|irb|R|rake)
$* ;;
cli)
shift
dyndoc-client $*;;
srv)
dyndoc-daemon $*;;
*) dyndoc-ruby $*;;
esac